### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by taikedz** [ShadowNinja/mt_media_collector#3]
Still trying to understand/fix this for myself (never done Rust before), but in the meantime I am having a build problem on Ubuntu 16.04, with a freshly installed `cargo` from repo:

	$ cargo build
		Updating registry `https://github.com/rust-lang/crates.io-index`
	 Downloading rust-ini v0.9.8
	 Downloading log v0.3.6
	 Downloading getopts v0.2.14
	 Downloading sha1 v0.2.0
	   Compiling getopts v0.2.14
	   Compiling log v0.3.6
	   Compiling sha1 v0.2.0
	   Compiling rust-ini v0.9.8
	   Compiling mt_media_collector v0.1.0 (file:///home/tai/gitprojects/mt_media_collector)
	src/main.rs:160:18: 165:3 error: match arms have incompatible types:
	 expected `fn(_, _) -> core::result::Result<(), std::io::error::Error> {copy_assets::symlink_file}`,
		found `fn(_, _) -> core::result::Result<(), std::io::error::Error> {std::fs::hard_link}`
	(expected fn item,
		found a different fn item) [E0308]
	src/main.rs:160 	let copy_func = match mode {
	src/main.rs:161 		AssetCopyMode::Symlink => symlink_file,
	src/main.rs:162 		AssetCopyMode::Hardlink => fs::hard_link,
	src/main.rs:163 		AssetCopyMode::Copy => copy_no_result,
	src/main.rs:164 		AssetCopyMode::None => return Ok(())
	src/main.rs:165 	};
	src/main.rs:160:18: 165:3 help: run `rustc --explain E0308` to see a detailed explanation
	src/main.rs:162:30: 162:43 note: match arm with an incompatible type
	src/main.rs:162 		AssetCopyMode::Hardlink => fs::hard_link,
		            		                           ^~~~~~~~~~~~~
	src/main.rs:168:8: 168:17 error: the type of this value must be known in this context
	src/main.rs:168 		try!(copy_func(&asset.path, path.join(to_hex(&asset.hash))));
		            		     ^~~~~~~~~
	src/main.rs:168:3: 168:64 note: in this expansion of try! (defined in <std macros>)
	error: aborting due to 2 previous errors
	Could not compile `mt_media_collector`.

**Comment by ShadowNinja** [comment]
Hmmm, what version are you running?  Git HEAD works on both the latest nightly compiler and the stable compiler for me.

**Comment by taikedz** [comment]
Cargo version is a nightly build from PPA https://launchpad.net/~jonathonf/+archive/ubuntu/rustlang

	cargo --version
	cargo 0.15.0-nightly (298a012 2016-12-20)

Error on building ansi_term

	/home/tai/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs:189:5: 189:23 error: user-defined types or type parameters cannot shadow the primitive types [E0317]
	/home/tai/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs:189     type str : ?Sized;
		                                                                                         ^~~~~~~~~~~~~~~~~~
	/home/tai/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs:189:5: 189:23 help: run `rustc --explain E0317` to see a detailed explanation
	   Compiling log v0.3.6
	error: aborting due to previous error
	Build failed, waiting for other jobs to finish...
	error: Could not compile `ansi_term`.

	To learn more, run the command again with --verbose.

**Comment by taikedz** [comment]
"nightly" build now

**Comment by ShadowNinja** [comment]
Does it work for you on stable or a recent nightly?  `1.16-nightly 2016-12-20`, `1.16-nightly 2017-02-02`, `1.14-stable`, and `1.15-stable` `rustc` versions work for me (note that `cargo` and `rustc`'s versions are separate and not kept in sync).

**Comment by taikedz** [comment]
OK proper nightly build works; needs the rustup.sh. Not *particularly* happy to use a non-repo method but I guess that's how this rolls.

Thanks
